#!/bin/bash
#Arquivo
arquivo="/tmp/teste2.tmp"
verde="\033[0;32m"

touch $arquivo
ps | grep php >> $arquivo 

while read linha; do
		id=$(echo $linha | awk '{print $1}')
		if kill $id; then
		echo -e "$verde -> Kill |Php PID: $id"
		fi
done < $arquivo

$rm $arquivo
touch $arquivo

ps | grep sass >> $arquivo 

while read linha; do
		id=$(echo $linha | awk '{print $1}')
		if kill $id; then
			echo -e "$verde -> Kill Sass PID: $id"
		fi
done < $arquivo

$rm $arquivo